<a target="_blank" href="https://colab.research.google.com/github/">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Tensorflow
# TensorFlow vs. PyTorch: A Tale of Two Deep Learning Giants 🧠🔍

---

# 1. Introduction: Tensor Math with a Sprinkle of Keras Magic  
At their core, **TensorFlow** and **PyTorch** are frameworks designed to perform *tensor algebra*—the lifeblood of deep learning.  
Tensors are fancy, multidimensional arrays that enable efficient data manipulation on GPUs.

- **TensorFlow**: Known for its robust **Keras** API, a high-level library for building models easily.  
  Think of Keras as LEGO bricks that make TensorFlow approachable for beginners and scalable for production.
  
- **PyTorch**: Offers a more Pythonic and intuitive interface, loved by researchers for its dynamic computation graph.  
  It’s like the Swiss Army knife for prototyping!

---

# 2. Attributes of Tensors: The Building Blocks of Deep Learning  
Tensors have several key attributes:  

- **Rank**: The number of dimensions a tensor has.  
  - Example: A scalar (single number) has rank 0, a vector has rank 1, and a matrix has rank 2.  

- **Order**: Synonymous with rank; another term for it.  

- **Shape**: The size of each dimension in the tensor.  
  For instance, a tensor with shape `(3, 4, 5)` has 3 dimensions.  

- **Datatype**: Tensors can store data of different types like `float32`, `int64`, etc.  

> **Fun Fact**: In PyTorch, `tensor.dtype` is like the recipe for your tensor, while `tensor.shape` tells you its serving size. 🍽️

---

# 3. Methods/Operations on Tensors: Math on Steroids  
Both frameworks excel at tensor operations. Here’s a taste of what you can do:  

- **Matrix Multiplication**:  
  - TensorFlow: `tf.matmul(a, b)`  
  - PyTorch: `torch.mm(a, b)`  

- **Element-wise Operations**:  
  Operations like addition, subtraction, etc., applied element by element.  

- **Gradients and Autograd**:  
  Both frameworks support automatic differentiation.  
  - TensorFlow: Handles gradients with `tf.GradientTape()`.  
  - PyTorch: Offers `torch.autograd` with dynamic computation graphs, perfect for experimentation.  

> PyTorch’s dynamic graph lets you modify the graph on the fly, while Tenso


## Importing libraries

In [34]:
import tensorflow as tf

In [35]:
import warnings
warnings.filterwarnings("ignore")

## Attributes & Data
Tensors have shapes. Some vocabulary:

Shape: The length (number of elements) of each of the axes of a tensor.

Rank: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.

Axis or Dimension: A particular dimension of a tensor.

Size: The total number of items in the tensor, the product of the shape vector's elements.


In [36]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])

In [37]:
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


In [38]:
tf.rank(x)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [39]:
x + x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [40]:
5 * x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 5., 10., 15.],
       [20., 25., 30.]], dtype=float32)>

In [41]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [42]:
tf.concat([x, x, x], axis=0)

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.],
       [1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [43]:
tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.6652409 ],
       [0.09003057, 0.24472848, 0.6652409 ]], dtype=float32)>

In [44]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [45]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [46]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU


Ragged Tensors
A tensor with variable numbers of elements along some axis is called "ragged". Use tf.ragged.RaggedTensor for ragged data.

For example, This cannot be represented as a regular tensor:

In [47]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [48]:
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


In [49]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


String tensors
tf.string is a dtype, which is to say you can represent data as strings (variable-length byte arrays) in tensors.

The strings are atomic and cannot be indexed the way Python strings are. The length of the string is not one of the axes of the tensor. See tf.strings for functions to manipulate them.

In [50]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


Sparse tensors:
Sometimes, your data is sparse, like a very wide embedding space. TensorFlow supports tf.sparse.SparseTensor and related operations to store sparse data efficiently.

In [51]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


## Operations
Normal tf.Tensor objects are immutable. To store model weights (or other mutable state) in TensorFlow use a tf.Variable.

In [60]:
var = tf.Variable(x)

In [61]:
var.assign(var+2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

In [62]:
var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

In [86]:
x = tf.Variable(2.0)

In [87]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [88]:
def f(x):
  y = x**2 + 2*x - 5
  return y
f(x)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [89]:
with tf.GradientTape() as tape:
  y = f(x)

g_x = tape.gradient(y, x)  # g(x) = dy/dx

In [90]:
g_x

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [91]:
@tf.function
def my_func(x):
  print('Tracing.\n')
  return tf.reduce_sum(x)

The first time you run the tf.function, although it executes in Python, it captures a complete, optimized graph representing the TensorFlow computations done within the function.